### ISSUE TITLE
Latest Testflight version crashes on start

### ISSUE THREAD

**Issue by cmoro-deusto** [somerobots/Trident#13]
I have just updated to the lastest avalaible version but it crashes on start

**Comment by somerobots** [comment]
Hey Carlos, sorry about that - you'll need to delete the app and reinstall it!

**Comment by cmoro-deusto** [comment]
Hi Matt. Thanks a lot, it works now.

**Comment by somerobots** [comment]
No problem! Just moving back into London this last week, development has slowed a bit, I will get back into it shortly :)

**Comment by cmoro-deusto** [comment]
:+1:
